apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 447079561480.dkr.ecr.ap-northeast-2.amazonaws.com/3team-flask
  newName: 447079561480.dkr.ecr.ap-northeast-2.amazonaws.com/3team-flask
  newTag: cfeb2f81
- name: 447079561480.dkr.ecr.ap-northeast-2.amazonaws.com/3team-nginx
  newName: 447079561480.dkr.ecr.ap-northeast-2.amazonaws.com/3team-nginx
  newTag: cfeb2f81
resources:
- ../../base
patchesStrategicMerge:
- flask-deployment-patch.yaml
- flask-service-patch.yaml
- nginx-deployment-patch.yaml
- flask-service-patch.yaml
