apiVersion: v1
kind: Service
metadata:
  name: team3-flask
  namespace: team3
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: team3-flask
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000