---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team3-flask
  namespace: team3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: team3-flask
  template:
    metadata:
      labels:
        app: team3-flask
    spec:
      containers:
      - name: nginx-flask-proxy
        image: 447079561480.dkr.ecr.ap-northeast-2.amazonaws.com/team3-flask
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: aws-secret-volume
          mountPath: "/home/aws/credentials"
      volumes:
        - name: aws-secret-volume
          secret:
            secretName: aws-credentials
      imagePullSecrets:
      - name: ecr-registry
      - name: aws-credentials