apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-flask-proxy-hpa
  namespace: team3
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-flask-proxy
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30