apiVersion: v1
kind: Service
metadata:
  name: nginx-flask-proxy
  namespace: team3
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: nginx-flask-proxy
  ports:
    - name: http
      protocol: TCP
      port: 8001
      targetPort: 8001